version: '3.0'

services:
  quin:
    container_name: quin-docker
    build: .
    ports:
      - "8080:8080"
      - "1212:1212"
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1212"
    command: '/bin/bash -c "/usr/bin/env chmod +x /project/wait-for-it.sh && /project/wait-for-it.sh mysql:3306 -t 25 && java -jar /app.jar"'
    volumes:
      - ./docker/provision/wait-for-it.sh:/project/wait-for-it.sh
    links:
      - mysql
  mysql:
    image: mysql:5.8
    ports:
      - "13306:3306"
    expose:
      - "13306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=activityMonitor
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"